#!/bin/bash
set -e
thisDirectory="${BASH_SOURCE%/*}"
fullPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

GO_SHA_256=56242ed5e41ef042f908fb99482769b85712b9b49449b97cdc2c0cc0d0c20001

function shaCheck {
  sha=$1
  path=$2

  detected=$(shasum -a 256 $path | awk '{print $1;}')

  if [ "$sha" == "$detected" ]; then
    echo "Sha's Match for $path"
  else
    echo "$path is invalid!"
    exit 1
  fi
}

export GOROOT=$fullPath/go
export GOBIN=$GOROOT/bin
export GOPATH=$fullPath/go/golang
export PATH=$PATH:$GOBIN

mkdir -p $GOROOT

if ! [ -x "$GOBIN/go" ]; then
  echo "Downloading go and gdrive CLI";
  tarGo="go1.9.3.linux-amd64.tar.gz"
  wget "https://dl.google.com/go/$tarGo"

  # shaCheck $GO_SHA_256 $tarGo

  tar -C $fullPath -xzf $tarGo
fi

if ! [ -x "$GOBIN/gdrive" ]; then
  go get github.com/prasmussen/gdrive
fi



# if [ "$DETECTED_SHA_SUM" == "$GDRIVE_SHA_SUM" ]; then
# echo "SHA matches, executable is safe."
# chmod +x gdrive

iso8601="$(date --iso-8601=seconds)"
hyphenatedDate="${iso8601//:/-}"
BACKUP_NAME="$hyphenatedDate-backup"
BACKUP_PATH="$thisDirectory/$BACKUP_NAME"
export PGPASSWORD=$DATA_DB_NANOBOX_PASS

echo "Dumping Database to $BACKUP_PATH"
# -Fc is custom format
pg_dump -Fc --file $BACKUP_PATH \
  --port 5432 --host $DATA_DB_HOST \
  --username $DATA_DB_NANOBOX_USER \
  --no-acl --no-owner \
  aeonvera_production

echo "Decrypting drive credentials..."
# Decrypt the drive service account json
ENCRYPTED_PATH="$thisDirectory/backup-service-account.enc"
UNENCRYPTED_PATH="$thisDirectory/account.json"
openssl enc \
  -in $ENCRYPTED_PATH \
  -d -aes-256-cbc -k $GOOGLE_DRIVE_SERVICE_ACCOUNT_PASSWORD > $UNENCRYPTED_PATH

mkdir -p ~/.gdrive
cp $UNENCRYPTED_PATH ~/.gdrive/

echo "Uploading to google drive..."
(
  $GOBIN/gdrive upload \
    --parent $BACKUP_FOLDER_NAME $BACKUP_PATH \
    --service-account $UNENCRYPTED_PATH
)

echo "Upload Complete"
# else
#   echo "SHA does not match. abort."
#
#   exit 1;
# fi


# Encrypt a file
# openssl enc -in $file -e -aes-256-cbc -k $password > encrypted-file-name
