#!/bin/bash
set -e
thisDirectory="${BASH_SOURCE%/*}"
fullPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"


iso8601="$(date --iso-8601=seconds)"
hyphenatedDate="${iso8601//:/-}"
BACKUP_NAME="$hyphenatedDate-backup"
BACKUP_PATH="$thisDirectory/$BACKUP_NAME"
export PGPASSWORD=$DATA_DB_NANOBOX_PASS

echo "Dumping Database to $BACKUP_PATH"
# -Fc is custom format
pg_dump -Fc --file $BACKUP_PATH \
  --port 5432 --host $DATA_DB_HOST \
  --username $DATA_DB_NANOBOX_USER \
  --no-acl --no-owner \
  aeonvera_production

echo "Decrypting drive credentials..."
# Decrypt the drive service account json
ENCRYPTED_PATH="$thisDirectory/backup-service-account.enc"
UNENCRYPTED_PATH="$thisDirectory/account.json"
openssl enc \
  -in $ENCRYPTED_PATH \
  -d -aes-256-cbc -k $GOOGLE_DRIVE_SERVICE_ACCOUNT_PASSWORD > $UNENCRYPTED_PATH

mkdir -p ~/.gdrive
cp $UNENCRYPTED_PATH ~/.gdrive/

echo "Uploading to google drive..."
(
  gdrive upload \
    --parent $BACKUP_FOLDER_NAME $BACKUP_PATH \
    --service-account $UNENCRYPTED_PATH
)

echo "Upload Complete"

# Encrypt a file
# openssl enc -in $file -e -aes-256-cbc -k $password > encrypted-file-name
