languages:
  Ruby: true
  JavaScript: false
  PHP: false
  Python: false

engines:
  rubocop:
    enabled: true

ratings:
  paths:
    - app/controllers/api/**/*
    - app/mailers/*
    - app/models/**/*
    - app/operations/**/*
    - app/policies/**/*
    - app/serializers/**/*
    - app/services/**/*


exclude_paths:
  - spec/
