AllCops:
  Exclude:
    - config/initializers/forbidden_yaml.rb
    - !ruby/regexp /(vendor|bundle|bin|db|tmp)\/.*/
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3

# sometimes, it's nice to be explicit with the difference between named args
# and a hash parameter
Style/BracesAroundHashParameters:
  Enabled: false

# Prefer short-arrow syntax (->) to the full `lambda` keyword
Style/Lambda:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Metrics/AbcSize:
  Max: 35 # TODO: Lower to 15

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 261 # TODO: Lower to 100

Metrics/CyclomaticComplexity:
  Max: 7 # TODO: Lower to 6

Metrics/LineLength:
  Max: 110 # TODO: Lower to 80

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 9 # TODO: Lower to 7

Layout/AlignHash:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/AlignParameters:
  EnforcedStyle: with_first_parameter

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/MissingElse:
  Enabled: false # TODO: maybe enable this?
  EnforcedStyle: case

Style/EmptyElse:
  EnforcedStyle: empty

Style/MultilineBlockLayout:
  Exclude:
    - spec/**/*

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/PredicateName:
  Enabled: false # TODO: enable with correct prefixes

Style/ClassVars:
  Enabled: false
