language: ruby
rvm:
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
env:
  - TRAVIS=true

before_srcipt:
  # - RAILS_ENV=test rake db:create; rake db:migrate
script:
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test rake db:drop
  - RAILS_ENV=test rake db:create
  - RAILS_ENV=test rake db:migrate
  - bundle exec rspec
  #- psql -c 'create database travis_ci_test;' -U postgres

bundler_args: "--local --without documentation"

addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 1eeb995da67e27b3df3f6cff8049df742e0aa73ce0e1505d2ffa2323b1a98896
  hosts:
    - test.local.vhost
    - testevent.test.local.vhost
    - edited.test.local.vhost

services:
  - redis-server

branches:
  only: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b7f4be974c0a0ac9c09c
  email:
    on_failure: change
