language: ruby
rvm:
  - 2.0
  - 2.2
script: bundle exec rspec
bundler_args: "--without documentation"
addons:
  code_climate:
    repo_token: {{CODECLIMATE_REPO_TOKEN}}
branches:
  only: master
notifications:
  email:
    on_failure: change
services:
  - redis-server
addons:
  postgresql: 9.3
