language: ruby
rvm:
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
env:
  - TRAVIS=true
  - CODECLIMATE_REPO_TOKEN={{CODECLIMATE_REPO_TOKEN}}

script: CODECLIMATE_REPO_TOKEN={{CODECLIMATE_REPO_TOKEN}} bundle exec rspec
bundler_args: "--local --without documentation"

addons:
  postgresql: 9.3
  code_climate:
    repo_token: {{CODECLIMATE_REPO_TOKEN}}
  hosts:
    - test.local.vhost
    - testevent.test.local.vhost
    - edited.test.local.vhost

services:
  - redis-server

branches:
  only: master

notifications:
  email:
    on_failure: change
