db:
  image: postgres:9.6
  ports:
    - "5432"
  volumes:
    - ./backups:/backups
  environment:
    POSTGRES_DB: aeonvera_development
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

redis:
  image: redis:3.2
  ports:
    - "16379:6379"
web:
  build: .
  dockerfile: ./Dockerfile
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/web
    - ./backups:/backups
  ports:
    - "3001:3001"
  links:
    - db
    - redis
    - redis:redis.local
  environment:
    - RAILS_ENV=development
    - REDIS_URL=redis://redis.local:6379

    - DATABASE_HOST=db
    - DATABASE_NAME=aeonvera_development
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=postgres
