version: '2'
services:
  db:
    image: postgres:9.6
    volumes:
      - ./backups:/backups
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: aeonvera_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
     - backend

  redis:
    image: redis:3.2
    networks:
     - backend

  rails: &rails
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
     - backend
    env_file:
      - .env
    volumes:
      - ./app:/web/app
      - ./bin:/web/bin
      - ./config:/web/config
      - ./coverage:/web/coverage
      - ./db:/web/db
      - ./lib:/web/lib
      - ./public:/web/public
      - ./scripts:/web/scripts
      - ./spec:/web/spec
      - ./vendor/assets:/web/vendor/assets

      - ./.rspec:/web/.rspec
      - ./.rspec_parallel:/web/.rspec_parallel
      - ./.rubocop.yml:/web/.rubocop.yml
      - ./.ruby-version:/web/.ruby-version
      - ./config.ru:/web/config.ru
      - ./Gemfile:/web/Gemfile
      - ./Gemfile.lock:/web/Gemfile.lock
      - ./Rakefile:/web/Rakefile

      - ./backups:/backups
    environment:
      # simulating heroku usage
      - THREADED_SIDEKIQ=true

      - RAILS_ENV=development
      - REDIS_URL=redis://redis.local:6379
      - REDIS_PROVIDER=redis://redis.local:6379
      - REDIS_HOST=redis.local
      - REDIS_PORT=6379

      - DATABASE_HOST=db.local
      - DATABASE_NAME=aeonvera_development
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432

      - SIDEKIQ_USERNAME=devuser
      - SIDEKIQ_PASSWORD=1234
      - SQREEN_LOG_LEVEL=DEBUG
      - SQREEN_LOG_LOCATION=/dev/stderr

  web:
    <<: *rails
    command: bundle exec rails s -p 4301 -b '0.0.0.0'
    # command: bundle exec puma -C ./config/puma.rb -b tcp://0.0.0.0:4301
    ports:
      - "4301:4301"
    env_file:
      - .env
    links:
      - db
      # - worker
      - db:db.local
      - redis
      - redis:redis.local

  # worker:
  #   <<: *rails
  #   command: bundle exec sidekiq
  #   links:
  #     - db
  #     - db:db.local
  #     - redis
  #     - redis:redis.local

networks:
  backend:
    driver: bridge
