#!/bin/bash
if [[ -n "$1" ]]; then
  echo "Running Command: $*"
  docker-compose -f docker-compose.dev.yml run --rm web $*
else
  echo "Booting Environment..."
  # make extra sure that the images are built
  docker-compose -f docker-compose.dev.yml build

  # start up everything
  docker-compose -f docker-compose.dev.yml up -d

  # allow for interactive binding.pry 'ing
  docker-compose -f docker-compose.dev.yml stop web
  docker-compose -f docker-compose.dev.yml run --rm --service-ports web
fi
