development:
  host: localhost
  port: 6379
development_remote:
  host: localhost
  port: 6379
development_public:
  host: localhost
  port: 6379
test:
  host: localhost
  port: 6379
staging:
  host: localhost
  port: 6379
production:
  host: localhost
  port: 6379
