MembershipReminderJob:
  every: ["2d"]
  queue: daemons
  description: "Membership Renewal Reminder"

OrderCleanupJob:
  every: ["1d"]
  queue: daemons
  description: "Cleans invalid and old orders"

DatabaseBackupJob:
  cron: '0 0 * * * *'
  queue: daemons
  description: "Back up the database"
