apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: gitlab
data:
  config.toml: |
    concurrent = 4

    [[runners]]
      name = "Kubernetes Runner"
      url = "https://gitlab.com/ci/"
      token = "S_arntLtzzEBBSi7HTf_"
      executor = "kubernetes"
      [runners.kubernetes]
        host = "https://45.67.34.123:4892"
        cert_file = "/etc/ssl/kubernetes/api.crt"
        key_file = "/etc/ssl/kubernetes/api.key"
        ca_file = "/etc/ssl/kubernetes/ca.crt"
        namespace = "gitlab"
        namespace_overwrite_allowed = "ci-.*"
        privileged = true
        cpu_limit = "1"
        memory_limit = "1Gi"
        service_cpu_limit = "1"
        service_memory_limit = "1Gi"
        helper_cpu_limit = "500m"
        helper_memory_limit = "100Mi"
        poll_interval = 5
        poll_timeout = 3600

        [runners.kubernetes.node_selector]
          gitlab = "true"

        [[runners.kubernetes.volumes.host_path]]
          name = "docker"
          mount_path = "/var/run/docker.sock"
