apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab-runner
  template:
    metadata:
      labels:
        name: gitlab-runner
    spec:
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: gitlab-runner

      - name: var-run-docker-sock
        hostPath:
          path: /var/run/docker.sock

      - name: working-directory
        hostPath:
          path: /home/gitlab-runner

      containers:
      - name: gitlab-runner
        args: ["run"]
        image: gitlab/gitlab-runner:latest
        imagePullPolicy: Always
        env:
        - name: GITLAB_URL
          value: https://gitlab.com/ci/
        - name: CI_SERVER_URL
          value: https://gitlab.com/ci/
        - name: GITLAB_CI_URL
          value: https://gitlab.com/ci/
        - name: REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: runner-registration-token
        volumeMounts:
        - name: var-run-docker-sock
          mountPath: /var/run/docker.sock
        - name: working-directory
          mountPath: /home/gitlab-runner
        - name: config
          mountPath: /etc/gitlab-runner
