apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-service
  labels:
    app: {{ .Values.appname }}
    component: {{ .Release.Name }}-redis-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: {{ .Values.appname }}
    component: {{ template "redis.name" . }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appname }}
  name: {{ template "redis.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ template "redis.name" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        component: {{ template "redis.name" . }}
    spec:
      containers:
      - name: {{ template "redis.name" . }}
        image: redis:3.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 20
        successThreshold: 1
          tcpSocket:
            port: {{ template "redis.name" . }}
          timeoutSeconds: 1
        ports:
        - containerPort: 6379
          name: {{ template "redis.name" . }}
          protocol: TCP
